DROP TABLE IF EXISTS University;

CREATE TABLE University (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(150) NOT NULL,
    OVERALL_SCORE DECIMAL(5,2) NOT NULL CHECK (OVERALL_SCORE >= 0 AND OVERALL_SCORE <= 100),
    CITY VARCHAR(100) NOT NULL,
    COUNTRY VARCHAR(100) NOT NULL
);